name: Test & Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'README.md'
      - '.vscode/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.40.5' # selfup { "regex": "\\d[^']+", "script": "deno --version | head -n 1 | cut -d ' ' -f 2" }
      - run: deno task cache
      - run: deno task build
      - name: Format
        run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Typecheck
        # https://github.com/orgs/community/discussions/25638#discussioncomment-3248564
        run: |
          shopt -s globstar
          deno check src/**/*.ts* test/**/*.ts*
      - name: Test
        run: deno test
