name: Test & Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'dprint.json'
      - '.eslintrc.js'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'dprint.json'
      - '.eslintrc.js'
      - 'README.md'
      - '.vscode/**'
jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'
  test:
    needs: [asdf-parser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).nodejs }}'
      - name: install dependencies
        run: npm ci --ignore-scripts
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run eslint
