name: Test & Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'dprint.json'
      - '.eslintrc.js'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'dprint.json'
      - '.eslintrc.js'
      - 'README.md'
      - '.vscode/**'
jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'
  test:
    needs: [asdf-parser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).bun }}'
      - run: bun install
      - name: Build # No test exists. So compiling is the all
        run: bun run build
      - name: Lint
        run: bun run eslint
