name: No Typo
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.16.17 # selfup { "regex": "\\d\\.\\d+\\.\\d+", "script": "typos --version | cut -d ' ' -f 2" }
        with:
          files: |
            .
            .github
            .vscode
