name: No Typo
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Keep same version as used in *.nix
      - uses: crate-ci/typos@v1.16.8
        with:
          files: |
            .
            .github
            .vscode
